---

- name: Check for pre-existing GoLang archive
  ansible.builtin.stat:
    path: /usr/local/go/README.md
  register: go_folder

- name: Create directory for GoLang install
  ansible.builtin.file:
    path: /usr/local/go
    state: directory
    mode: '0644'
  when: not go_folder.stat.exists

- name: Download and expand GoLang archive
  ansible.builtin.unarchive:
    src: https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local/go
    remote_src: true
    extra_opts:
      - --strip-components=1
  when: not go_folder.stat.exists

- name: Create ~/.bashrc file if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: touch
    mode: '0644'

- name: Add GoLang paths to bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export GOROOT=/usr/local/go
      export GOPATH=$HOME/go
      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
  tags: bashrc

- name: Reload bashrc
  # Tell ansible-lint to skip the shell check since command will not work with source
  ansible.builtin.shell: . "{{ ansible_env.HOME }}/.bashrc" # noqa command-instead-of-shell
  changed_when: false
  tags: bashrc
